unitNames = {
    'Alioni': ['Alioni'],
    'Arden': ['Arden'],
    'Arthur': ['Arthur'],
    'Athena': ['Athena'],
    'Ban': ['Ban'],
    'Beatrice': ['Beatrice'],
    'Bellion': ['Bellion'],
    'Benimaru': ['Benimaru'],
    'Brunhild': ['Brunhild'],
    'Cain': ['Cain'],
    'Camila': ['Camila'],
    'Chandler': ['Chandler'],
    'Cusack': ['Cusack'],
    'Deathpierce': ['Deathpierce'],
    'Deldry': ['Deldry'],
    'Denzel': ['Denzel'],
    'Derieri': ['Derieri'],
    'Diane': ['Diane'],
    'Dogedo': ['Dogedo'],
    'Dreyfus': ['Dreyfus'],
    'Drole': ['Drole'],
    'Eastin': ['Eastin'],
    'Echidna': ['Echidna'],
    'Elaine': ['Elaine'],
    'Eleven': ['Eleven'],
    'Elizabeth': ['Elizabeth'],
    'ElizabethHawk': ['ElizabethHawk'],
    'Ellatte': ['Ellatte'],
    'Emilia': ['Emilia'],
    'Eren': ['Eren'],
    'Escanor': ['Escanor'],
    'Estarossa': ['Estarossa'],
    'Filo': ['Filo'],
    'Fraudrin': ['Fraudrin'],
    'Freesia': ['Freesia'],
    'Freya':['Freya'],
    'Freyr': ['Freyr'],
    'Galland': ['Galland'],
    'Gerharde': ['Gerharde'],
    'Gilthunder': ['Gilthunder'],
    'Gloxinia': ['Gloxinia'],
    'Golgius': ['Golgius'],
    'Gowther': ['Gowther'],
    'Griamore': ['Griamore'],
    'Guila': ['Guila'],
    'Gustaf': ['Gustaf'],
    'Hawk': ['Hawk', 'Hawkslo'],
    'Helbram': ['Helbram'],
    'Hendrickson': ['Hendrickson'],
    'Howzer': ['Howzer'],
    'Hugo': ['Hugo'],
    'Jormungandr': ['Jormungandr'],
    'Jericho': ['Jericho'],
    'Jenna': ['Jenna'],
    'Jillian': ['Jillian'],
    'Jim': ['Jim'],
    'Jude': ['Jude'],
    'King': ['King'],
    'Kizuna':['Kizuna'],
    'Kyo': ['Kyo'],
    'Levi': ['Levi'],
    'Lillia': ['Lillia'],
    'Ludociel': ['Ludociel'],
    'Liz': ['Liz\d'],
    'Mai': ['Mai'],
    'Marmas': ['Marmas'],
    'Matrona': ['Matrona'],
    'Mael':['Mael'],
    'Megellda': ['Megellda'],
    'Melascula': ['Melascula'],
    'Meliodas': ['Meliodas'],
    'Merlin': ['Merlin'],
    'Mikasa': ['Mikasa'],
    'Mike': ['Mike'],
    'Milim': ['Milim'],
    'Mono': ['Mono'],
    'Monspeet': ['Monspeet'],
    'Nanashi': ['Nanashi'],
    'Naofumi': ['Naofumi'],
    'Ram': ['Ram'],
    'Raphtalia': ['Raphtalia'],
    'Reinhard': ['Reinhard'],
    'Rem': ['Rem'],
    'Rimuru': ['Rimuru', 'Slimuru'],
    'Roxy': ['Roxy'],
    'Rugal': ['Rugal'],
    'Ruin': ['Ruin'],
    'Sariel': ['Sariel'],
    'Shin': ['Shin'],
    'Shuna': ['Shuna'],
    'Simon': ['Simon'],
    'Sigurd': ['Sigurd'],
    'Skadi': ['Skadi'],
    'Slater': ['Slater'],
    'Taizoo': ['Taizoo'],
    'Tarmiel': ['Tarmiel'],
    'Terry': ['Terry'],
    'Twigo': ['Twigo'],
    'Thonar': ['Thonar'],
    'Valenti': ['Valenti'],
    'Vivian': ['Vivian'],
    'Waillo': ['Waillo'],
    'Weinheidt': ['Weinheidt'],
    'Will': ['Will'],
    'Iori Yagami': ['Yagami'],
    'Zaneri': ['Zaneri'],
    'Zaratras': ['Zaratras'],
    'Zeldris': ['Zeldris']
}
incompatibilities = [
    ['Fraudrin', 'Dreyfus'],
    ['ElizabethHawk', 'Elizabeth', 'Liz'],
    ['ElizabethHawk', 'Hawk']
]

attributeColors = {
    'Vitality': 'Green',
    'Strength': 'Red',
    'Speed': 'Blue',
    'Dark': 'Dark',
    'Light': 'Light'
}
